# Generated by Django 2.1 on 2019-03-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('position', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('hall_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='webapp.Hall')),
            ],
        ),
    ]
