# Generated by Django 2.1 on 2019-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='line',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='seat',
            name='position',
            field=models.IntegerField(max_length=2),
        ),
    ]
