# Generated by Django 2.1 on 2019-03-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190303_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_deleted', models.BooleanField(default=False)),
                ('hall_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Hall')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Hall'),
        ),
    ]
