# Generated by Django 2.1 on 2019-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190304_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
