# Generated by Django 2.1 on 2019-03-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190304_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webapp.Category'),
            preserve_default=False,
        ),
    ]
