# Generated by Django 2.1 on 2019-03-07 07:36

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20190307_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default=webapp.models.generate_code, editable=False, max_length=12, unique_for_date='created_at'),
        ),
    ]
