# Generated by Django 2.1 on 2019-03-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_book_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_finish', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='webapp.Discount')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='webapp.Seat')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='webapp.Show')),
            ],
        ),
    ]
