# Generated by Django 2.1 on 2019-03-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_discount_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_finish',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_start',
            field=models.DateTimeField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
