# Generated by Django 2.1 on 2019-03-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20190307_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category_name',
            new_name='categories',
        ),
    ]
