# Generated by Django 2.1 on 2019-03-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20190313_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='categories',
            new_name='category_name',
        ),
    ]
